In [41]:
import warnings
warnings.filterwarnings('ignore')

In [42]:
import numpy as np
import pandas as pd
from pathlib import Path
from collections import Counter

In [43]:
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import confusion_matrix
from imblearn.metrics import classification_report_imbalanced

# Read the CSV and Perform Basic Data Cleaning

In [44]:
# https://help.lendingclub.com/hc/en-us/articles/215488038-What-do-the-different-Note-statuses-mean-

columns = [
    "loan_amnt", "int_rate", "installment", "home_ownership",
    "annual_inc", "verification_status", "issue_d", "loan_status",
    "pymnt_plan", "dti", "delinq_2yrs", "inq_last_6mths",
    "open_acc", "pub_rec", "revol_bal", "total_acc",
    "initial_list_status", "out_prncp", "out_prncp_inv", "total_pymnt",
    "total_pymnt_inv", "total_rec_prncp", "total_rec_int", "total_rec_late_fee",
    "recoveries", "collection_recovery_fee", "last_pymnt_amnt", "next_pymnt_d",
    "collections_12_mths_ex_med", "policy_code", "application_type", "acc_now_delinq",
    "tot_coll_amt", "tot_cur_bal", "open_acc_6m", "open_act_il",
    "open_il_12m", "open_il_24m", "mths_since_rcnt_il", "total_bal_il",
    "il_util", "open_rv_12m", "open_rv_24m", "max_bal_bc",
    "all_util", "total_rev_hi_lim", "inq_fi", "total_cu_tl",
    "inq_last_12m", "acc_open_past_24mths", "avg_cur_bal", "bc_open_to_buy",
    "bc_util", "chargeoff_within_12_mths", "delinq_amnt", "mo_sin_old_il_acct",
    "mo_sin_old_rev_tl_op", "mo_sin_rcnt_rev_tl_op", "mo_sin_rcnt_tl", "mort_acc",
    "mths_since_recent_bc", "mths_since_recent_inq", "num_accts_ever_120_pd", "num_actv_bc_tl",
    "num_actv_rev_tl", "num_bc_sats", "num_bc_tl", "num_il_tl",
    "num_op_rev_tl", "num_rev_accts", "num_rev_tl_bal_gt_0",
    "num_sats", "num_tl_120dpd_2m", "num_tl_30dpd", "num_tl_90g_dpd_24m",
    "num_tl_op_past_12m", "pct_tl_nvr_dlq", "percent_bc_gt_75", "pub_rec_bankruptcies",
    "tax_liens", "tot_hi_cred_lim", "total_bal_ex_mort", "total_bc_limit",
    "total_il_high_credit_limit", "hardship_flag", "debt_settlement_flag"
]

target = ["loan_status"]

In [45]:
# Load the data
file_path = Path('../Module-17-Challenge-Resources/LoanStats_2019Q1.csv')
df = pd.read_csv(file_path, skiprows=1)[:-2]
df = df.loc[:, columns].copy()

# Drop the null columns where all values are null
df = df.dropna(axis='columns', how='all')

# Drop the null rows
df = df.dropna()

# Remove the `Issued` loan status
issued_mask = df['loan_status'] != 'Issued'
df = df.loc[issued_mask]

# convert interest rate to numerical
df['int_rate'] = df['int_rate'].str.replace('%', '')
df['int_rate'] = df['int_rate'].astype('float') / 100


# Convert the target column values to low_risk and high_risk based on their values
x = {'Current': 'low_risk'}   
df = df.replace(x)

x = dict.fromkeys(['Late (31-120 days)', 'Late (16-30 days)', 'Default', 'In Grace Period'], 'high_risk')    
df = df.replace(x)

df.reset_index(inplace=True, drop=True)

df.head()

,loan_amnt,int_rate,installment,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,dti,...,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,debt_settlement_flag
0,10500.0,0.1719,375.35,RENT,66000.0,Source Verified,Mar-2019,low_risk,n,27.24,...,85.7,100.0,0.0,0.0,65687.0,38199.0,2000.0,61987.0,N,N
1,25000.0,0.2000,929.09,MORTGAGE,105000.0,Verified,Mar-2019,low_risk,n,20.23,...,91.2,50.0,1.0,0.0,271427.0,60641.0,41200.0,49197.0,N,N
2,20000.0,0.2000,529.88,MORTGAGE,56000.0,Verified,Mar-2019,low_risk,n,24.26,...,66.7,50.0,0.0,0.0,60644.0,45684.0,7500.0,43144.0,N,N
3,10000.0,0.1640,353.55,RENT,92000.0,Verified,Mar-2019,low_risk,n,31.44,...,100.0,50.0,1.0,0.0,99506.0,68784.0,19700.0,76506.0,N,N
4,22000.0,0.1474,520.39,MORTGAGE,52000.0,Not Verified,Mar-2019,low_risk,n,18.76,...,100.0,0.0,0.0,0.0,219750.0,25919.0,27600.0,20000.0,N,N

# Split the Data into Training and Testing

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 68817 entries, 0 to 68816
Data columns (total 86 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   loan_amnt                   68817 non-null  float64
 1   int_rate                    68817 non-null  float64
 2   installment                 68817 non-null  float64
 3   home_ownership              68817 non-null  object
 4   annual_inc                  68817 non-null  float64
 5   verification_status         68817 non-null  object
 6   issue_d                     68817 non-null  object
 7   loan_status                 68817 non-null  object
 8   pymnt_plan                  68817 non-null  object
 9   dti                         68817 non-null  float64
 10  delinq_2yrs                 68817 non-null  float64
 11  inq_last_6mths              68817 non-null  float64
 12  open_acc                    68817 non-null  float64
 13  pub_rec                     68817 non-null  float64
 14  revol_bal                   68817 non-null  float64
 15  total_acc                   68817 non-null  float64
 16  initial_list_status         68817 non-null  object
 17  out_prncp                   68817 non-null  float64
 18  out_prncp_inv               68817 non-null  float64
 19  total_pymnt                 68817 non-null  float64
 20  total_pymnt_inv             68817 non-null  float64
 21  total_rec_prncp             68817 non-null  float64
 22  total_rec_int               68817 non-null  float64
 23  total_rec_late_fee          68817 non-null  float64
 24  recoveries                  68817 non-null  float64
 25  collection_recovery_fee     68817 non-null  float64
 26  last_pymnt_amnt             68817 non-null  float64
 27  next_pymnt_d                68817 non-null  object
 28  collections_12_mths_ex_med  68817 non-null  float64
 29  policy_code                 68817 non-null  float64
 30  application_type            68817 non-null  object
 31  acc_now_delinq              68817 non-null  float64
 32  tot_coll_amt                68817 non-null  float64
 33  tot_cur_bal                 68817 non-null  float64
 34  open_acc_6m                 68817 non-null  float64
 35  open_act_il                 68817 non-null  float64
 36  open_il_12m                 68817 non-null  float64
 37  open_il_24m                 68817 non-null  float64
 38  mths_since_rcnt_il          68817 non-null  float64
 39  total_bal_il                68817 non-null  float64
 40  il_util                     68817 non-null  float64
 41  open_rv_12m                 68817 non-null  float64
 42  open_rv_24m                 68817 non-null  float64
 43  max_bal_bc                  68817 non-null  float64
 44  all_util                    68817 non-null  float64
 45  total_rev_hi_lim            68817 non-null  float64
 46  inq_fi                      68817 non-null  float64
 47  total_cu_tl                 68817 non-null  float64
 48  inq_last_12m                68817 non-null  float64
 49  acc_open_past_24mths        68817 non-null  float64
 50  avg_cur_bal                 68817 non-null  float64
 51  bc_open_to_buy              68817 non-null  float64
 52  bc_util                     68817 non-null  float64
 53  chargeoff_within_12_mths    68817 non-null  float64
 54  delinq_amnt                 68817 non-null  float64
 55  mo_sin_old_il_acct          68817 non-null  float64
 56  mo_sin_old_rev_tl_op        68817 non-null  float64
 57  mo_sin_rcnt_rev_tl_op       68817 non-null  float64
 58  mo_sin_rcnt_tl              68817 non-null  float64
 59  mort_acc                    68817 non-null  float64
 60  mths_since_recent_bc        68817 non-null  float64
 61  mths_since_recent_inq       68817 non-null  float64
 62  num_accts_ever_120_pd       68817 non-null  float64
 63  num_actv_bc_tl              68817 non-null  float64
 64  num_actv_rev_tl             68817 non-null  float64
 65  num_bc_sats                 68817 non-null  float64
 66  num_bc_tl                   68817 non-null  float64
 67  num_il_tl                   68817 non-null  float64
 68  num_op_rev_tl               68817 non-null  float64
 69  num_rev_accts               68817 non-null  float64
 70  num_rev_tl_bal_gt_0         68817 non-null  float64
 71  num_sats                    68817 non-null  float64
 72  num_tl_120dpd_2m            68817 non-null  float64
 73  num_tl_30dpd                68817 non-null  float64
 74  num_tl_90g_dpd_24m          68817 non-null  float64
 75  num_tl_op_past_12m          68817 non-null  float64
 76  pct_tl_nvr_dlq              68817 non-null  float64
 77  percent_bc_gt_75            68817 non-null  float64
 78  pub_rec_bankruptcies        68817 non-null  float64
 79  tax_liens                   68817 non-null  float64
 80  tot_hi_cred_lim             68817 non-null  float64
 81  total_bal_ex_mort           68817 non-null  float64
 82  total_bc_limit              68817 non-null  float64
 83  total_il_high_credit_limit  68817 non-null  float64
 84  hardship_flag               68817 non-null  object
 85  debt_settlement_flag        68817 non-null  object
dtypes: float64(76), object(10)
memory usage: 45.2+ MB

In [47]:
# Create our features
X_df = df.drop(columns=['loan_status'])
#X= pd.get_dummies(X_df, columns= ['home_ownership', 'verification_status','issue_d', 'debt_settlement_flag', 'hardship_flag', 'application_type', 'next_pymnt_d', 'initial_list_status', 'pymnt_plan'], drop_first = True)
X= pd.get_dummies(X_df)

# Create our target
y = df['loan_status'].to_frame()

In [48]:
X.describe()

,loan_amnt,int_rate,installment,annual_inc,dti,delinq_2yrs,inq_last_6mths,open_acc,pub_rec,revol_bal,...,issue_d_Mar-2019,pymnt_plan_n,initial_list_status_f,initial_list_status_w,next_pymnt_d_Apr-2019,next_pymnt_d_May-2019,application_type_Individual,application_type_Joint App,hardship_flag_N,debt_settlement_flag_N
count,68817.000000,68817.000000,68817.000000,6.881700e+04,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,...,68817.000000,68817.0,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.0,68817.0
mean,16677.594562,0.127718,480.652863,8.821371e+04,21.778153,0.217766,0.497697,12.587340,0.126030,17604.142828,...,0.177238,1.0,0.123879,0.876121,0.383161,0.616839,0.860340,0.139660,1.0,1.0
std,10277.348590,0.048130,288.062432,1.155800e+05,20.199244,0.718367,0.758122,6.022869,0.336797,21835.880400,...,0.381873,0.0,0.329446,0.329446,0.486161,0.486161,0.346637,0.346637,0.0,0.0
min,1000.000000,0.060000,30.890000,4.000000e+01,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000,...,0.000000,1.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.0,1.0
25%,9000.000000,0.088100,265.730000,5.000000e+04,13.890000,0.000000,0.000000,8.000000,0.000000,6293.000000,...,0.000000,1.0,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000,1.0,1.0
50%,15000.000000,0.118000,404.560000,7.300000e+04,19.760000,0.000000,0.000000,11.000000,0.000000,12068.000000,...,0.000000,1.0,0.000000,1.000000,0.000000,1.000000,1.000000,0.000000,1.0,1.0
75%,24000.000000,0.155700,648.100000,1.040000e+05,26.660000,0.000000,1.000000,16.000000,0.000000,21735.000000,...,0.000000,1.0,0.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.0,1.0
max,40000.000000,0.308400,1676.230000,8.797500e+06,999.000000,18.000000,5.000000,72.000000,4.000000,587191.000000,...,1.000000,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.0,1.0

In [49]:
# Check the balance of our target values
y['loan_status'].value_counts()

low_risk     68470
high_risk      347
Name: loan_status, dtype: int64

In [55]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

# Ensemble Learners

In this section, you will compare two ensemble algorithms to determine which algorithm results in the best performance. You will train a Balanced Random Forest Classifier and an Easy Ensemble AdaBoost classifier . For each algorithm, be sure to complete the folliowing steps:

1. Train the model using the training data. 
2. Calculate the balanced accuracy score from sklearn.metrics.
3. Print the confusion matrix from sklearn.metrics.
4. Generate a classication report using the `imbalanced_classification_report` from imbalanced-learn.
5. For the Balanced Random Forest Classifier onely, print the feature importance sorted in descending order (most important feature to least important) along with the feature score

Note: Use a random state of 1 for each algorithm to ensure consistency between tests

### Balanced Random Forest Classifier

In [96]:
# Resample the training data with the BalancedRandomForestClassifier
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaler = scaler.fit(X_train)
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

# Resample the training data with the RandomOversampler
from imblearn.ensemble import BalancedRandomForestClassifier

brfc = BalancedRandomForestClassifier(n_estimators =100)
random_forest= brfc.fit(X_train_scaled, y_train)
BalancedRandomForestClassifier(random_state=1)

BalancedRandomForestClassifier(random_state=1)

In [97]:
# Calculated the balanced accuracy score
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

y_pred = random_forest.predict(X_test_scaled)
accuracy_score(y_test, y_pred)

0.8755594303981401

In [98]:
# Display the confusion matrix
confusion_matrix(y_test, y_pred)

array([[   70,    34],
       [ 2107, 14994]])

In [99]:
# Print the imbalanced classification report
from imblearn.metrics import classification_report_imbalanced

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

   high_risk       0.03      0.67      0.06       104
    low_risk       1.00      0.88      0.93     17101

    accuracy                           0.88     17205
   macro avg       0.51      0.77      0.50     17205
weighted avg       0.99      0.88      0.93     17205

In [100]:
# List the features sorted in descending order by feature importance
sorted(zip(model.feature_importances_, X.columns), reverse=True)

[(0.07095543920193573, 'total_rec_prncp'),
 (0.06267153399634508, 'total_pymnt'),
 (0.06263954792755376, 'total_rec_int'),
 (0.0569329707456252, 'total_pymnt_inv'),
 (0.056851031090222146, 'last_pymnt_amnt'),
 (0.0236747350361278, 'int_rate'),
 (0.01946282248316521, 'issue_d_Jan-2019'),
 (0.018706196362754102, 'dti'),
 (0.017333048069161805, 'max_bal_bc'),
 (0.01659803274772601, 'installment'),
 (0.016127862015429886, 'mo_sin_old_rev_tl_op'),
 (0.0157479209175456, 'annual_inc'),
 (0.01563188938559379, 'bc_util'),
 (0.015521006383032915, 'out_prncp'),
 (0.015326831446839023, 'out_prncp_inv'),
 (0.014717928002628788, 'il_util'),
 (0.01469864143127917, 'tot_hi_cred_lim'),
 (0.014361650367322292, 'bc_open_to_buy'),
 (0.014282016658542488, 'revol_bal'),
 (0.014118758619057363, 'issue_d_Mar-2019'),
 (0.013748940035044515, 'total_bc_limit'),
 (0.013595819325788886, 'avg_cur_bal'),
 (0.013454384997587169, 'tot_cur_bal'),
 (0.013420677015490814, 'mths_since_rcnt_il'),
 (0.013333504851462898, 'mths_since_recent_inq'),
 (0.013148464586095265, 'mo_sin_old_il_acct'),
 (0.012950952995261276, 'total_bal_ex_mort'),
 (0.012718299091079223, 'total_rev_hi_lim'),
 (0.012214287249006162, 'total_il_high_credit_limit'),
 (0.011684867514687291, 'total_bal_il'),
 (0.011573627218846102, 'all_util'),
 (0.011164208237209847, 'loan_amnt'),
 (0.010838074716249594, 'mths_since_recent_bc'),
 (0.010597383585252432, 'total_rec_late_fee'),
 (0.01058648960645567, 'num_rev_accts'),
 (0.010426851831536032, 'mo_sin_rcnt_rev_tl_op'),
 (0.010369374573583804, 'num_il_tl'),
 (0.010295871845387437, 'total_acc'),
 (0.009321993386438437, 'num_sats'),
 (0.009218809608106329, 'mo_sin_rcnt_tl'),
 (0.0091042832095621, 'num_op_rev_tl'),
 (0.009059855784474189, 'num_rev_tl_bal_gt_0'),
 (0.008869257352840595, 'acc_open_past_24mths'),
 (0.008676918335552649, 'open_acc'),
 (0.008454072754692683, 'open_il_24m'),
 (0.008393241892019093, 'num_bc_tl'),
 (0.008275793275370168, 'num_actv_rev_tl'),
 (0.00784499232209664, 'num_actv_bc_tl'),
 (0.007840011641498484, 'num_bc_sats'),
 (0.007664492883637093, 'pct_tl_nvr_dlq'),
 (0.007488036489550803, 'num_tl_op_past_12m'),
 (0.007132833335509184, 'inq_last_12m'),
 (0.007039731580612645, 'mort_acc'),
 (0.006947391171200802, 'total_cu_tl'),
 (0.006816939058375692, 'inq_fi'),
 (0.006791912620547147, 'percent_bc_gt_75'),
 (0.006785923729879076, 'open_act_il'),
 (0.006388623855615188, 'open_rv_24m'),
 (0.006341973624895834, 'next_pymnt_d_May-2019'),
 (0.00538005453186184, 'next_pymnt_d_Apr-2019'),
 (0.005218788026507333, 'open_acc_6m'),
 (0.004809349273026392, 'issue_d_Feb-2019'),
 (0.004787120524497509, 'inq_last_6mths'),
 (0.004580902551044508, 'delinq_2yrs'),
 (0.004253172383642283, 'open_il_12m'),
 (0.00405225855163657, 'num_accts_ever_120_pd'),
 (0.003966711740408549, 'open_rv_12m'),
 (0.003784410608266636, 'tot_coll_amt'),
 (0.0028841333341331444, 'verification_status_Verified'),
 (0.00197669082419025, 'verification_status_Not Verified'),
 (0.0019363019364841531, 'home_ownership_RENT'),
 (0.0019247246780575496, 'home_ownership_OWN'),
 (0.0018099161820704897, 'pub_rec_bankruptcies'),
 (0.0017274870208373644, 'verification_status_Source Verified'),
 (0.0016468347530260226, 'pub_rec'),
 (0.0015411310814175917, 'application_type_Joint App'),
 (0.0013665339493586827, 'application_type_Individual'),
 (0.0013328500221244368, 'home_ownership_MORTGAGE'),
 (0.0013051354937592336, 'initial_list_status_f'),
 (0.001168367516643053, 'initial_list_status_w'),
 (0.0009648551666174637, 'num_tl_90g_dpd_24m'),
 (0.0004006435577921872, 'collections_12_mths_ex_med'),
 (0.00013036077377760126, 'chargeoff_within_12_mths'),
 (0.0001122354424317154, 'home_ownership_ANY'),
 (0.0, 'tax_liens'),
 (0.0, 'recoveries'),
 (0.0, 'pymnt_plan_n'),
 (0.0, 'policy_code'),
 (0.0, 'num_tl_30dpd'),
 (0.0, 'num_tl_120dpd_2m'),
 (0.0, 'hardship_flag_N'),
 (0.0, 'delinq_amnt'),
 (0.0, 'debt_settlement_flag_N'),
 (0.0, 'collection_recovery_fee'),
 (0.0, 'acc_now_delinq')]

### Easy Ensemble AdaBoost Classifier

In [103]:
# Train the EasyEnsembleClassifier
from imblearn.ensemble import EasyEnsembleClassifier

model = EasyEnsembleClassifier(base_estimator=None, n_estimators=100, n_jobs=1, random_state=1, 
                                   replacement=False, sampling_strategy='auto', verbose=0, 
                                   warm_start=False)

model.fit(X_train_scaled, y_train)
y_pred = model.predict(X_test_scaled)

EasyEnsembleClassifier(n_estimators=100, random_state=1)

EasyEnsembleClassifier(n_estimators=100, random_state=1)

In [104]:
# Calculated the balanced accuracy score
from sklearn.metrics import balanced_accuracy_score
y_pred = model.predict(X_test_scaled)
balanced_accuracy_score(y_test, y_pred)

0.9178773283613644

In [106]:
# Display the confusion matrix
confusion_matrix(y_test, y_pred)

array([[   93,    11],
       [ 1000, 16101]])

In [108]:
# Print the imbalanced classification report
from imblearn.metrics import classification_report_imbalanced
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

   high_risk       0.09      0.89      0.16       104
    low_risk       1.00      0.94      0.97     17101

    accuracy                           0.94     17205
   macro avg       0.54      0.92      0.56     17205
weighted avg       0.99      0.94      0.96     17205